site_name: Draft Civic Transparency Schemas
site_description: Draft Testing Schemas for the Civic Transparency project
site_author: Civic Interconnect
site_url: https://civic-interconnect.github.io/civic-transparency-spec/
repo_url: https://github.com/civic-interconnect/civic-transparency-spec
edit_uri: edit/main/docs/en/

theme:
  name: material
  language: en
  favicon: img/favicon.png
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - content.footer
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs.stick
  copyright: Copyright &copy; 2025 Civic Interconnect

nav:
- Home: index.md
- Privacy: docs/privacy.md
- Specs:
  - Schemas (Index): specs/index.md
  - Provenance Tag: specs/provenance_tag.md
  - Series: specs/series.md
  - Transparency API: specs/transparency_api.md

docs_dir: docs/en

plugins:
  - search
  - include-markdown
  - minify:
      minify_html: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: true
      enable_creation_date: false
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_signature: true
            group_by_category: true
            filters: ["!^_"]  # hide private members
      
markdown_extensions:
- admonition
- codehilite
- pymdownx.snippets
- pymdownx.tabbed
- toc
