# .github/workflows/ci.yml
name: Civic Transparency Spec CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Linting with Ruff
      - name: Lint with Ruff
        run: ruff check .

      # Validate Schemas (using Python)
      - name: Validate JSON Schemas (Draft-07)
        run: python .github/scripts/validate_schemas.py
      - name: Validate OpenAPI
        run: python .github/scripts/validate_open_api.py

      # Run Tests
      - name: Run Tests
        run: pytest --cov --cov-report=xml
      - name: Codecov Upload
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          
      # Build Documentation (sanity check)
      - name: Build Docs (Sanity Check)
        run: mkdocs build
