# .github/workflows/ci.yml
name: Civic Transparency Spec CI (Lint, Test, Coverage)
# Runs on every push to the main branch and on pull requests.
# First line of defense, catches issues before they reach release.
# Designed to fail fast, run all tests, and generate coverage reports.
# It does not fix issues, only checks them.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout (full history with tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python and cache ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Assemble. Install dev deps (extras, non-editable)
        run: |
          pip install ".[dev]"

      - name: Baseline. Ruff lint (fail fast, check only, no format or auto-fix in CI)
        run: ruff check .

      - name: Validate. JSON Schema validation
        run: |
          check-jsonschema --schemafile https://json-schema.org/draft/2020-12/schema \
            src/ci/transparency/spec/schemas/*.schema.json

      - name: Baseline. Run tests (include any validation and coverage)
        run: pytest -q

      - name: Coverage. Generate summary
        run: python .github/scripts/coverage_summary.py

      - name: Coverage. Build HTML
        run: coverage html

      - name: Coverage. Combine and Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports-${{ matrix.python-version }}
          path: |
            coverage.xml
            htmlcov/
          overwrite: true

      - name: Deploy. Build docs (sanity check)
        run: mkdocs build

