# .github/workflows/deploy-docs.yml
name: Deploy CT Spec Docs with Mike

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mike requires full history

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs and Mike
        run: pip install -r requirements.txt

      - name: Deploy Docs with Mike
        run: |
          # The branch name will become the version alias (e.g., 'main' -> 'latest')
          # To use a version number, you'd extract it from a tag or other source
          mike deploy --push --update-aliases latest ${{ github.ref_name }}